//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DutchVACCATISGenerator.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ATIS {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ATIS() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DutchVACCATISGenerator.Resources.ATIS", typeof(ATIS).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to END OF INFORMATION.
        /// </summary>
        internal static string END {
            get {
                return ResourceManager.GetString("END", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXTRA (VOICE ONLY).
        /// </summary>
        internal static string EXTRA {
            get {
                return ResourceManager.GetString("EXTRA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAIN LANDING RUNWAY.
        /// </summary>
        internal static string MLR {
            get {
                return ResourceManager.GetString("MLR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAIN TAKEOFF RUNWAY.
        /// </summary>
        internal static string MTR {
            get {
                return ResourceManager.GetString("MTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SECONDARY LANDING RUNWAY.
        /// </summary>
        internal static string SLR {
            get {
                return ResourceManager.GetString("SLR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SECONDARY TAKEOFF RUNWAY.
        /// </summary>
        internal static string STR {
            get {
                return ResourceManager.GetString("STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TRANSITION LEVEL.
        /// </summary>
        internal static string TL {
            get {
                return ResourceManager.GetString("TL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WIND.
        /// </summary>
        internal static string WIND {
            get {
                return ResourceManager.GetString("WIND", resourceCulture);
            }
        }
    }
}
