//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DutchVACCATISGenerator.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ICAO {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ICAO() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DutchVACCATISGenerator.Resources.ICAO", typeof(ICAO).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THIS IS SCHIPHOL INFORMATION.
        /// </summary>
        internal static string EHAM {
            get {
                return ResourceManager.GetString("EHAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THIS IS BEEK INFORMATION.
        /// </summary>
        internal static string EHBK {
            get {
                return ResourceManager.GetString("EHBK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THIS IS EINDHOVEN INFORMATION.
        /// </summary>
        internal static string EHEH {
            get {
                return ResourceManager.GetString("EHEH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THIS IS EELDE INFORMATION.
        /// </summary>
        internal static string EHGG {
            get {
                return ResourceManager.GetString("EHGG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THIS IS ROTTERDAM INFORMATION.
        /// </summary>
        internal static string EHRD {
            get {
                return ResourceManager.GetString("EHRD", resourceCulture);
            }
        }
    }
}
