//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DutchVACCATISGenerator.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Phenomena {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Phenomena() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DutchVACCATISGenerator.Resources.Phenomena", typeof(Phenomena).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PATCHES.
        /// </summary>
        internal static string BC {
            get {
                return ResourceManager.GetString("BC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BLOWING.
        /// </summary>
        internal static string BL {
            get {
                return ResourceManager.GetString("BL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MIST.
        /// </summary>
        internal static string BR {
            get {
                return ResourceManager.GetString("BR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOW DRIFTING.
        /// </summary>
        internal static string DR {
            get {
                return ResourceManager.GetString("DR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DUSTSTORM.
        /// </summary>
        internal static string DS {
            get {
                return ResourceManager.GetString("DS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WIDESPREAD DUST.
        /// </summary>
        internal static string DU {
            get {
                return ResourceManager.GetString("DU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DRIZZLE.
        /// </summary>
        internal static string DZ {
            get {
                return ResourceManager.GetString("DZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FUNNEL CLOUD.
        /// </summary>
        internal static string FC {
            get {
                return ResourceManager.GetString("FC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FOG.
        /// </summary>
        internal static string FG {
            get {
                return ResourceManager.GetString("FG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMOKE.
        /// </summary>
        internal static string FU {
            get {
                return ResourceManager.GetString("FU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FREEZING.
        /// </summary>
        internal static string FZ {
            get {
                return ResourceManager.GetString("FZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HAIL.
        /// </summary>
        internal static string GR {
            get {
                return ResourceManager.GetString("GR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOFT HAIL.
        /// </summary>
        internal static string GS {
            get {
                return ResourceManager.GetString("GS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HAZE.
        /// </summary>
        internal static string HZ {
            get {
                return ResourceManager.GetString("HZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ICE CRYSTALS.
        /// </summary>
        internal static string IC {
            get {
                return ResourceManager.GetString("IC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SHALLOW.
        /// </summary>
        internal static string MI {
            get {
                return ResourceManager.GetString("MI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ICE PELLETS.
        /// </summary>
        internal static string PL {
            get {
                return ResourceManager.GetString("PL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DUST.
        /// </summary>
        internal static string PO {
            get {
                return ResourceManager.GetString("PO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PARTIAL.
        /// </summary>
        internal static string PR {
            get {
                return ResourceManager.GetString("PR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SPRAY.
        /// </summary>
        internal static string PY {
            get {
                return ResourceManager.GetString("PY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RAIN.
        /// </summary>
        internal static string RA {
            get {
                return ResourceManager.GetString("RA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAND.
        /// </summary>
        internal static string SA {
            get {
                return ResourceManager.GetString("SA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SNOW GRAINS.
        /// </summary>
        internal static string SG {
            get {
                return ResourceManager.GetString("SG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SHOWERS.
        /// </summary>
        internal static string SH {
            get {
                return ResourceManager.GetString("SH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SNOW.
        /// </summary>
        internal static string SN {
            get {
                return ResourceManager.GetString("SN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQUALL.
        /// </summary>
        internal static string SQ {
            get {
                return ResourceManager.GetString("SQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SANDSTORM.
        /// </summary>
        internal static string SS {
            get {
                return ResourceManager.GetString("SS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THUNDERSTORMS.
        /// </summary>
        internal static string TS {
            get {
                return ResourceManager.GetString("TS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UNKOWN PRECIPITATION.
        /// </summary>
        internal static string UP {
            get {
                return ResourceManager.GetString("UP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VOLCANIC ASH.
        /// </summary>
        internal static string VA {
            get {
                return ResourceManager.GetString("VA", resourceCulture);
            }
        }
    }
}
